parameters:
    templating.helper.slots.class: AdvancedForm\CoreBundle\Helpers\SlotsHelper

services:
    twig_timer:
        class: AdvancedForm\CoreBundle\Helpers\TwigHelper
        public: false
        tags:
            - { name: twig.extension }

    advanced_form.type.tax_class:
        class: AdvancedForm\CoreBundle\Form\TaxClassType
        arguments: [ @doctrine.orm.entity_manager ]
        tags:
            - { name: form.type, alias: tax_class }

    advanced_form.type.tax_rule:
        class: AdvancedForm\CoreBundle\Form\TaxRuleType
        arguments: [ @doctrine.orm.entity_manager ]
        tags:
            - { name: form.type, alias: tax_rule }
